//! # Flow Field
//!
//! Pre-computed vector flow field using 8-Connected Chamfer Dijkstra
//! and Central Difference Gradient for smooth 360° direction vectors.
//!
//! ## Ownership
//! - **Task:** task_03_flow_field_registry
//! - **Contract:** implementation_plan.md → Contract 4
//!
//! **File Size Rationale:** This module implements a single Dijkstra-based flow field
//! algorithm. The 500+ lines are due to the integration field computation + inline tests.
//! All functions share the same `FlowField` data structure. Keep as single file.
//!
//! ## Algorithm
//! 1. Integration Field: Multi-source Chamfer Dijkstra (BinaryHeap)
//!    - Orthogonal cost: 10, Diagonal cost: 14
//!    - Anti-corner-cutting for diagonal obstacle traversal
//! 2. Direction Field: Central Difference Gradient
//!    - Produces smooth 360° analog vectors (not 8-way snapping)
//!    - OOB/obstacle neighbors use current_cost (wall avoidance)

use bevy::platform::collections::HashMap; // AHash (hashbrown) — fast integer key lookups
use bevy::prelude::*;
use std::cmp::Ordering;
use std::collections::{BinaryHeap, HashSet};

/// Min-heap state for Dijkstra's algorithm.
///
/// `BinaryHeap` is a max-heap by default, so we reverse the
/// `Ord` implementation to get min-heap behavior.
#[derive(Copy, Clone, Eq, PartialEq)]
struct CostState {
    cost: u32,
    cell: IVec2,
}

impl Ord for CostState {
    fn cmp(&self, other: &Self) -> Ordering {
        // Reverse ordering for min-heap
        other
            .cost
            .cmp(&self.cost)
            .then_with(|| self.cell.x.cmp(&other.cell.x))
            .then_with(|| self.cell.y.cmp(&other.cell.y))
    }
}

impl PartialOrd for CostState {
    fn partial_cmp(&self, other: &Self) -> Option<Ordering> {
        Some(self.cmp(other))
    }
}

/// 8-connected neighbor offsets with Chamfer distance costs.
///
/// Orthogonal (cardinal) = 10 ≈ 1.0 × 10
/// Diagonal = 14 ≈ √2 × 10 ≈ 1.414 × 10
///
/// Integer arithmetic only — no floating-point in integration phase.
const NEIGHBORS_8: [(i32, i32, u32); 8] = [
    // Cardinal (cost 10)
    (0, -1, 10),
    (0, 1, 10),
    (-1, 0, 10),
    (1, 0, 10),
    // Diagonal (cost 14)
    (-1, -1, 14),
    (1, -1, 14),
    (-1, 1, 14),
    (1, 1, 14),
];

/// Pre-computed vector flow field for mass pathfinding.
///
/// Each cell stores a normalized direction vector pointing toward
/// the nearest goal. Entities sample their cell to get movement
/// direction. NOT a Resource — owned by `FlowFieldRegistry`.
///
/// ## Coordinate System
/// - Flat array indexed as `[y * width + x]`
/// - World-to-cell: `⌊world_pos / cell_size⌋`
/// - Cell `(0,0)` covers world area `[0, cell_size) × [0, cell_size)`
#[derive(Debug)]
pub struct FlowField {
    pub width: u32,
    pub height: u32,
    pub cell_size: f32,
    /// Direction vectors, indexed as `[y * width + x]`.
    /// Each vector is normalized (length 1.0) or `Vec2::ZERO`.
    /// Generated by Central Difference Gradient — smooth 360° angles.
    pub directions: Vec<Vec2>,
    /// Integration field costs (Chamfer distance to nearest goal).
    /// Scale: orthogonal=10, diagonal=14. Goal cells=0.
    /// `u16::MAX` = unreachable. True distance ≈ `cost / 10.0`.
    pub costs: Vec<u16>,
}

impl FlowField {
    /// Allocate a new flow field with zeroed vectors and costs.
    pub fn new(width: u32, height: u32, cell_size: f32) -> Self {
        let size = (width * height) as usize;
        Self {
            width,
            height,
            cell_size,
            directions: vec![Vec2::ZERO; size],
            costs: vec![0u16; size],
        }
    }

    /// Compute the flow field from goal positions, routing around obstacles and terrain costs.
    pub fn calculate(&mut self, goals: &[Vec2], obstacles: &[IVec2], cost_map: Option<&[u16]>) {
        // ── Phase 1: Integration Field (Chamfer Dijkstra) ──
        self.costs.iter_mut().for_each(|c| *c = u16::MAX);

        let obstacle_set: HashSet<IVec2> = obstacles.iter().copied().collect();
        let mut heap = BinaryHeap::new();

        // Seed all goal cells at cost 0
        for &goal_world in goals {
            let gx = (goal_world.x / self.cell_size).floor() as i32;
            let gy = (goal_world.y / self.cell_size).floor() as i32;
            let cell = IVec2::new(gx, gy);

            if self.in_bounds(cell) && !obstacle_set.contains(&cell) {
                let idx = self.cell_index(cell);
                if self.costs[idx] != 0 {
                    self.costs[idx] = 0;
                    heap.push(CostState { cost: 0, cell });
                }
            }
        }

        // Dijkstra expansion with Chamfer weights
        while let Some(CostState { cost, cell }) = heap.pop() {
            let idx = self.cell_index(cell);
            // Skip stale entries (already found a shorter path)
            if cost > self.costs[idx] as u32 {
                continue;
            }

            for &(dx, dy, move_cost) in &NEIGHBORS_8 {
                let neighbor = IVec2::new(cell.x + dx, cell.y + dy);

                if !self.in_bounds(neighbor) || obstacle_set.contains(&neighbor) {
                    continue;
                }

                // Anti-corner-cutting: block diagonal if adjacent ortho is obstacle
                if move_cost == 14 {
                    let adj_x = IVec2::new(cell.x + dx, cell.y);
                    let adj_y = IVec2::new(cell.x, cell.y + dy);
                    if obstacle_set.contains(&adj_x) || obstacle_set.contains(&adj_y) {
                        continue;
                    }
                }

                // ── NEW: Terrain cost integration (pure integer) ──
                let terrain_penalty = cost_map
                    .map(|cm| cm[self.cell_index(neighbor)])
                    .unwrap_or(100);

                // Absolute wall — skip entirely (never enters BFS queue)
                if terrain_penalty == u16::MAX {
                    continue;
                }

                // Integer math: (10 × 200) / 100 = 20 (double cost for mud)
                let effective_cost = (move_cost * terrain_penalty as u32) / 100;
                let next_cost = cost.saturating_add(effective_cost);
                let n_idx = self.cell_index(neighbor);

                if next_cost < self.costs[n_idx] as u32 {
                    self.costs[n_idx] = next_cost as u16;
                    heap.push(CostState {
                        cost: next_cost,
                        cell: neighbor,
                    });
                }
            }
        }

        // ── Phase 2: Direction Field (Central Difference Gradient) ──
        for y in 0..self.height as i32 {
            for x in 0..self.width as i32 {
                let cell = IVec2::new(x, y);
                let idx = self.cell_index(cell);
                let current_cost = self.costs[idx];

                if current_cost == u16::MAX || current_cost == 0 {
                    self.directions[idx] = Vec2::ZERO;
                    continue;
                }

                // get_cost: use current_cost for OOB/obstacle neighbors
                // This gracefully pushes vectors away from walls
                let get_cost = |nx: i32, ny: i32| -> u16 {
                    let n = IVec2::new(nx, ny);
                    if self.in_bounds(n) && !obstacle_set.contains(&n) {
                        let neighbor_cost =
                            cost_map.map(|cm| cm[self.cell_index(n)]).unwrap_or(100);
                        if neighbor_cost == u16::MAX {
                            current_cost
                        } else {
                            self.costs[self.cell_index(n)]
                        }
                    } else {
                        current_cost
                    }
                };

                let left = get_cost(x - 1, y) as f32;
                let right = get_cost(x + 1, y) as f32;
                let up = get_cost(x, y - 1) as f32;
                let down = get_cost(x, y + 1) as f32;

                // Water flows downhill: high cost → low cost
                let grad_x = left - right;
                let grad_y = up - down;

                self.directions[idx] = Vec2::new(grad_x, grad_y).normalize_or_zero();
            }
        }
    }

    /// Sample the flow field at a world position.
    ///
    /// Returns the direction vector for the cell containing `world_pos`.
    /// Returns `Vec2::ZERO` if position is out of grid bounds.
    pub fn sample(&self, world_pos: Vec2) -> Vec2 {
        let cx = (world_pos.x / self.cell_size).floor() as i32;
        let cy = (world_pos.y / self.cell_size).floor() as i32;

        if cx < 0 || cx >= self.width as i32 || cy < 0 || cy >= self.height as i32 {
            return Vec2::ZERO;
        }

        self.directions[(cy as u32 * self.width + cx as u32) as usize]
    }

    /// Check if a cell coordinate is within grid bounds.
    #[inline]
    fn in_bounds(&self, cell: IVec2) -> bool {
        cell.x >= 0 && cell.x < self.width as i32 && cell.y >= 0 && cell.y < self.height as i32
    }

    /// Convert cell coordinate to flat array index.
    #[inline]
    fn cell_index(&self, cell: IVec2) -> usize {
        (cell.y as u32 * self.width + cell.x as u32) as usize
    }
}

/// Registry of flow fields, keyed by target faction ID.
///
/// Each field converges on entities of that faction.
/// Deduplication is automatic: multiple follower factions targeting
/// faction 1 share ONE flow field for faction 1.
#[derive(Resource, Debug, Default)]
pub struct FlowFieldRegistry {
    pub fields: HashMap<u32, FlowField>,
}

// ── Tests ──────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_single_goal_center_adjacent_directions() {
        // Arrange — 5×5 grid, cell_size=1.0, goal at (2.5, 2.5) → cell (2,2)
        let mut ff = FlowField::new(5, 5, 1.0);

        // Act
        ff.calculate(&[Vec2::new(2.5, 2.5)], &[], None);

        // Assert — Goal cell: cost=0, direction=ZERO
        assert_eq!(ff.costs[2 * 5 + 2], 0, "Goal cell cost must be 0");
        assert_eq!(
            ff.sample(Vec2::new(2.5, 2.5)),
            Vec2::ZERO,
            "Goal direction must be ZERO"
        );

        // Cell (1,2): left of goal → positive x
        let dir = ff.sample(Vec2::new(1.5, 2.5));
        assert!(
            dir.x > 0.0,
            "Cell left of goal should point right, got {:?}",
            dir
        );

        // Cell (3,2): right of goal → negative x
        let dir = ff.sample(Vec2::new(3.5, 2.5));
        assert!(
            dir.x < 0.0,
            "Cell right of goal should point left, got {:?}",
            dir
        );

        // Cell (2,1): above goal → positive y
        let dir = ff.sample(Vec2::new(2.5, 1.5));
        assert!(
            dir.y > 0.0,
            "Cell above goal should point down, got {:?}",
            dir
        );

        // Cell (2,3): below goal → negative y
        let dir = ff.sample(Vec2::new(2.5, 3.5));
        assert!(
            dir.y < 0.0,
            "Cell below goal should point up, got {:?}",
            dir
        );
    }

    #[test]
    fn test_corner_cell_diagonal_direction() {
        // Arrange
        let mut ff = FlowField::new(5, 5, 1.0);

        // Act
        ff.calculate(&[Vec2::new(2.5, 2.5)], &[], None);

        // Assert
        let dir = ff.sample(Vec2::new(0.5, 0.5));
        assert!(
            dir.x > 0.0 && dir.y > 0.0,
            "Corner should point diagonally toward goal, got {:?}",
            dir
        );

        // Verify ~45° (gradient produces smooth diagonal)
        let ratio = dir.x / dir.y;
        assert!((ratio - 1.0).abs() < 0.1, "Should be ~45°, ratio={}", ratio);
    }

    #[test]
    fn test_multiple_goals_nearest_wins() {
        // Arrange
        let mut ff = FlowField::new(10, 1, 1.0);

        // Act
        ff.calculate(&[Vec2::new(0.5, 0.5), Vec2::new(9.5, 0.5)], &[], None);

        // Assert
        let dir3 = ff.sample(Vec2::new(3.5, 0.5));
        assert!(dir3.x < 0.0, "Cell 3 closer to goal 0, should point left");

        let dir7 = ff.sample(Vec2::new(7.5, 0.5));
        assert!(dir7.x > 0.0, "Cell 7 closer to goal 9, should point right");
    }

    #[test]
    fn test_edge_cells_direction() {
        // Arrange
        let mut ff = FlowField::new(5, 5, 1.0);

        // Act
        ff.calculate(&[Vec2::new(0.5, 0.5)], &[], None);

        // Assert
        let dir = ff.sample(Vec2::new(4.5, 0.5));
        assert!(dir.x < 0.0, "Right edge should point left toward goal");
    }

    #[test]
    fn test_out_of_bounds_returns_zero() {
        // Arrange
        let ff = FlowField::new(5, 5, 1.0);

        // Assert
        assert_eq!(ff.sample(Vec2::new(-1.0, 2.0)), Vec2::ZERO);
        assert_eq!(ff.sample(Vec2::new(2.0, -1.0)), Vec2::ZERO);
        assert_eq!(ff.sample(Vec2::new(5.0, 2.0)), Vec2::ZERO);
        assert_eq!(ff.sample(Vec2::new(2.0, 5.0)), Vec2::ZERO);
    }

    #[test]
    fn test_goal_cell_returns_zero() {
        // Arrange
        let mut ff = FlowField::new(5, 5, 1.0);

        // Act
        ff.calculate(&[Vec2::new(2.5, 2.5)], &[], None);

        // Assert
        assert_eq!(
            ff.sample(Vec2::new(2.5, 2.5)),
            Vec2::ZERO,
            "Goal cell must be ZERO"
        );
    }

    #[test]
    fn test_obstacle_blocks_and_routes_around() {
        // Arrange
        let mut ff = FlowField::new(5, 3, 1.0);

        // Act
        ff.calculate(&[Vec2::new(4.5, 1.5)], &[IVec2::new(2, 1)], None);

        // Assert — Obstacle cell should have MAX cost
        assert_eq!(ff.costs[5 + 2], u16::MAX, "Obstacle must have MAX cost");

        // Cell (1,1) near obstacle should route around
        let dir = ff.sample(Vec2::new(1.5, 1.5));
        assert!(
            dir.x > 0.0 || dir.y.abs() > 0.01,
            "Should route around obstacle, got {:?}",
            dir
        );
    }

    #[test]
    fn test_registry_stores_by_faction() {
        // Arrange
        let mut registry = FlowFieldRegistry::default();

        // Act
        registry.fields.insert(0, FlowField::new(5, 5, 1.0));
        registry.fields.insert(1, FlowField::new(10, 10, 2.0));

        // Assert
        assert_eq!(registry.fields.len(), 2);
        assert_eq!(registry.fields.get(&0).unwrap().width, 5);
        assert_eq!(registry.fields.get(&1).unwrap().width, 10);
    }

    #[test]
    fn test_performance_50x50_grid() {
        // Arrange
        let mut ff = FlowField::new(50, 50, 1.0);

        // Act
        ff.calculate(&[Vec2::new(25.0, 25.0)], &[], None);

        // Assert
        assert_eq!(ff.costs[25 * 50 + 25], 0, "Goal must be cost 0");
        assert!(ff.costs[0] > 0, "Corner should have positive cost");

        // Verify Chamfer distance at corner (0,0): ~25 diag × 14 = 350
        let corner = ff.costs[0];
        assert!(
            corner > 300 && corner < 400,
            "Corner Chamfer cost should be ~350, got {}",
            corner
        );
    }

    #[test]
    fn test_cost_map_none_backward_compatible() {
        // Arrange
        let mut ff1 = FlowField::new(5, 5, 1.0);
        let mut ff2 = FlowField::new(5, 5, 1.0);

        // Act
        ff1.calculate(&[Vec2::new(2.5, 2.5)], &[], None);
        ff2.calculate(&[Vec2::new(2.5, 2.5)], &[], Some(&[100; 25]));

        // Assert
        assert_eq!(ff1.costs, ff2.costs);
        assert_eq!(ff1.directions, ff2.directions);
    }

    #[test]
    fn test_cost_map_200_doubles_chamfer_cost() {
        // Arrange
        let mut ff = FlowField::new(3, 1, 1.0);
        let costs = vec![100, 200, 100]; // Middle cell is mud (200)

        // Act - Goal at right end
        ff.calculate(&[Vec2::new(2.5, 0.5)], &[], Some(&costs));

        // Assert
        // Cell 2 (goal) = 0
        // Cell 1 (mud) = 10 * 200 / 100 = 20
        // Cell 0 = 20 + 10 * 100 / 100 = 30
        assert_eq!(ff.costs[1], 20, "Mud cell should have cost 20");
        assert_eq!(ff.costs[0], 30, "Clear cell should have cost 30");
    }

    #[test]
    fn test_cost_map_max_acts_as_wall() {
        // Arrange
        let mut ff = FlowField::new(3, 1, 1.0);
        let costs = vec![100, u16::MAX, 100]; // Middle cell is wall (MAX)

        // Act
        ff.calculate(&[Vec2::new(2.5, 0.5)], &[], Some(&costs));

        // Assert
        assert_eq!(ff.costs[1], u16::MAX, "Wall cell should have MAX cost");
        assert_eq!(
            ff.costs[0],
            u16::MAX,
            "Cell blocked by wall should be unreachable"
        );
    }

    #[test]
    fn test_cost_map_125_slightly_increases_cost() {
        // Arrange
        let mut ff = FlowField::new(3, 1, 1.0);
        let costs = vec![100, 125, 100]; // Middle cell is pushable (125)

        // Act
        ff.calculate(&[Vec2::new(2.5, 0.5)], &[], Some(&costs));

        // Assert
        // Cell 2 (goal) = 0
        // Cell 1 = 10 * 125 / 100 = 12
        // Cell 0 = 12 + 10 = 22
        assert_eq!(ff.costs[1], 12);
        assert_eq!(ff.costs[0], 22);
    }
}
